### ISSUE TITLE
如何扩展配置中心，比如etcd等

### ISSUE THREAD

**Issue by dudiao** [longtai-cn/hippo4j#184]
如何扩展配置中心，比如etcd，或者直接 http 接口刷新

**Comment by longtai-cn** [comment]
@dudiao 如果使用 hippo4j-core，可以通过继承 `AbstractCoreThreadPoolDynamicRefresh` 完成动态刷新

**Comment by dudiao** [comment]
核心是不是调用这个方法就行了：`AbstractCoreThreadPoolDynamicRefresh#dynamicRefresh`

**Comment by longtai-cn** [comment]
> 核心是不是调用这个方法就行了：`AbstractCoreThreadPoolDynamicRefresh#dynamicRefresh`

是的，如果需要的话，我可以把相关逻辑加入到下个版本。

**Comment by dudiao** [comment]
谢谢了，目前还在调研阶段，不过我们公司etcd client那块是自研的，扩展的话需要自己写了

**Comment by longtai-cn** [comment]
> 谢谢了，目前还在调研阶段，不过我们公司etcd client那块是自研的，扩展的话需要自己写了

好嘞，有需要随时沟通。
