### ISSUE TITLE
线程资源通过线程池创建，不允许自行显示创建线程

### ISSUE THREAD

**Issue by longtai-cn** [longtai-cn/hippo4j#194]
修改测试用例显示创建线程，应使用单个线程的线程池来创建。
1. cn.hippo4j.example.core.inittest.RunStateHandlerTest#runTask
2. cn.hippo4j.example.core.inittest.TaskDecoratorTest#taskDecoratorTest

**Comment by zhuanghaozhe** [comment]
Hello, I would like to contribute in this issue

**Comment by longtai-cn** [comment]
@zhuanghaozhe Welcome.
