### ISSUE TITLE
客户端不同环境持有不同的线程池参数配置

### ISSUE THREAD

**Issue by yanyunliu** [longtai-cn/hippo4j#220]
## Question Report

在开始报告问题之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/longtai-cn/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Server
### 你使用了哪个版本？
最新2.1
### 预期行为
客户端 的不同环境 配置的线程池参数不一样   --> 比如 预发环境 线程池max =10  正式环境配置 max=100  

### 实际行为
由于不同环境都是 根据相同的 租户、项目、线程池id 查询的hippo4j 的 同一个线程池配置   max=100；  会导致预发环境最终配置的还是 max=100 ，同预期的max=10不符；

### 原因分析（如果可以）
 按照现有hippo4j 功能，似乎需要 新建两个项目，然后 客户端配置 租户、项目、线程池id 时不同环境配置不同项目id ，这样可以实现客户端不同环境的线程池参数不一致；
 但是这样似乎不符合项目id的语义
 线程池配置中加个环境标识是否更合适一些？

**Comment by longtai-cn** [comment]
@yanyunliu 有两种方案供参考：

1. hippo4j server 应该需要按环境部署，比如说 Test、Pre、Uat、Prod 这种。
2. 按照我的理解，预发环境和生产是要保持一致的。如果说预发和生产共用 hippo4j server，区分线程池配置似乎没有必要。

能列举一些更具体的场景么？

**Comment by yanyunliu** [comment]
预发和生产共用 hippo4j server，区分线程池配置  ， 个人认为也是没有必要；
具体场景等到后续使用时再行观察吧；

**Comment by longtai-cn** [comment]
嗯嗯。目前线程池实例已经添加了环境标识，如果说验证预发环境，可以在实例管理中只修改预发节点参数。
