### ISSUE TITLE
报警配置 alarm=false  不配置通知报警平台和接收人就报错

### ISSUE THREAD

**Issue by lhzsdnu** [longtai-cn/hippo4j#241]
## Bug Report

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/longtai-cn/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Core
### 你使用了哪个版本？
1.2.1
### 预期行为
alarm=false  可以不配置 notify-platforms 和 receive

### 实际行为
![image](https://user-images.githubusercontent.com/20517550/169691549-a3c01dac-fec5-4277-bdb3-17146b547b21.png)

### 问题重现步骤
问题1:  删除  notify-platforms
问题2:  删除  receive: xxx

**Comment by longtai-cn** [comment]
该问题会在 1.3.0 解决

**Comment by longtai-cn** [comment]
done
