### ISSUE TITLE
服务端页面字段未显示中文

### ISSUE THREAD

**Issue by lhzsdnu** [longtai-cn/hippo4j#242]
## Bug Report

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/longtai-cn/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Server
### 你使用了哪个版本？
1.2.1
### 实际行为
![image](https://user-images.githubusercontent.com/20517550/169691786-40e84b34-da16-4277-932d-5522242c09f2.png)

**Comment by longtai-cn** [comment]
感谢建议，1.3.0 修复

**Comment by longtai-cn** [comment]
done
